"""
HSX Insider Trading — NotebookLM PDF Extractor

Reads the latest hsx_insider_trading_*.json produced by hsx_insider_scraper.py,
downloads each PDF, uploads it to NotebookLM via Playwright, extracts structured
transaction data using INSIDER_PROMPT, and writes an enriched JSON file.

Prerequisites:
    1. Google auth session at ~/.notebooklm-mcp/storage_state.json
       and ~/.notebooklm-mcp/auth.json
       (generated by the refresh_nlm_auth helper — see README in cloned repo)
    2. playwright install chromium   (run once)

Usage:
    python hsx_nlm_extractor.py                       # auto-finds latest JSON
    python hsx_nlm_extractor.py --input PATH          # explicit JSON path
    python hsx_nlm_extractor.py --workers 3           # parallel workers
    python hsx_nlm_extractor.py --dry-run             # skip NLM, test plumbing
"""
from __future__ import annotations

import argparse
import glob
import json
import logging
import os
import re
import sys
import threading
import time
import unicodedata
import urllib.parse
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(threadName)s] %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────────────
AUTH_DIR = Path.home() / ".notebooklm-mcp"
STORAGE_STATE_PATH = AUTH_DIR / "storage_state.json"
AUTH_JSON_PATH = AUTH_DIR / "auth.json"

BASE_URL = "https://notebooklm.google.com"
BATCHEXECUTE_URL = f"{BASE_URL}/_/LabsTailwindUi/data/batchexecute"

RPC_CREATE   = "CCqFvf"
RPC_GET_NB   = "rLM1Ne"
RPC_DELETE_NB = "WWINqb"

INDEX_POLL_INTERVAL = 5
INDEX_POLL_MAX      = 300
QUERY_TIMEOUT_MS    = 180_000

PDF_DIR   = Path("./pdfs")
OUTDIR    = "./"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
}

# ── Prompt ────────────────────────────────────────────────────────────────────
INSIDER_PROMPT = """TASK: Extract all insider/related-party stock transaction notifications from the attached PDF document.
The document may contain multiple transaction notifications for different individuals (e.g., in a table format for ESOP or group filings).

Extract a list of transaction records. For each transaction, extract:
1. "ticker": Stock symbol of the company (e.g., "NAB").
2. "name": Full name of the transacting person (e.g., "Do Xuan Khanh").
3. "relationship": Position or relationship of the person to the company. Extract this in Vietnamese exactly as written in the PDF (e.g., "Cha ruột", "Người ủy quyền công bố thông tin", "Phó Tổng giám đốc cấp cao"). Do NOT translate to English.
4. "action": "buy" if purchasing/registering to buy/receiving, "sell" if selling/disposing.
5. "change_volume": Absolute number of shares registered/expected to be traded (e.g., 48500).
6. "after_volume": Total number of shares expected to be held after the transaction (e.g., 48500).
7. "after_percentage": Expected ownership percentage after the transaction (e.g., "0.0%").
8. "date_range": Expected transaction date range or period in format MM/DD~MM/DD (e.g., "04/24~05/05" or "06/04~07/03").
9. "company_fullname": Full name of the listed company (e.g., "Nam A Commercial Joint Stock Bank").
10. "exchange": The exchange name (e.g., "HSX", "HNX", "UPCoM").

Rules:
- Vietnamese text must be NFC-normalized.
- Dates in YYYY-MM-DD or MM/DD~MM/DD format.
- Output a JSON object with a key "transactions" containing the list of transactions.
- OUTPUT ONLY THE RAW JSON OBJECT. No preamble, no markdown fences, no explanation.
- Your response MUST start with { and end with }
"""


# ── PDF download ──────────────────────────────────────────────────────────────

def download_pdf(url: str, dest: Path) -> bool:
    """Download PDF from staticfile.hsx.vn and verify signature."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=30)
        if resp.status_code != 200:
            log.error(f"HTTP {resp.status_code} downloading {url}")
            return False
        if b"%PDF" not in resp.content[:1024]:
            log.error(f"Not a valid PDF: {url}")
            return False
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(resp.content)
        return True
    except Exception as e:
        log.error(f"Download failed for {url}: {e}")
        return False


# ── RPC helpers (ported from notebooklm_pdf_worker.py) ───────────────────────

def _get_session_params(html: str, auth: dict) -> tuple[str, str, str]:
    m = re.search(r'boq_labs[^\s"\']+', html)
    bl = m.group(0) if m else "boq_labs-tailwind-frontend_20260511.12_p0"
    csrf = auth.get("csrf_token", "")
    sid  = auth.get("session_id", "")
    m = re.search(r'"SNlM0e":"([^"]+)"', html)
    if m:
        csrf = m.group(1)
    m = re.search(r'"FdrFJe":"([^"]+)"', html)
    if m:
        sid = m.group(1)
    return bl, csrf, sid


def _build_url(rpc_id: str, bl: str, sid: str, source_path: str = "/") -> str:
    params = {
        "rpcids": rpc_id, "source-path": source_path,
        "bl": bl, "hl": "en",
        "_reqid": str(int(time.time() * 1000) % 1_000_000), "rt": "c",
    }
    if sid:
        params["f.sid"] = sid
    return f"{BATCHEXECUTE_URL}?{urllib.parse.urlencode(params)}"


def _build_body(rpc_id: str, params: list, csrf: str) -> str:
    f_req = [[[rpc_id, json.dumps(params, separators=(",", ":")), None, "generic"]]]
    body = f"f.req={urllib.parse.quote(json.dumps(f_req, separators=(',', ':')), safe='')}"
    if csrf:
        body += f"&at={urllib.parse.quote(csrf, safe='')}"
    return body + "&"


def _post_rpc(context, url: str, body: str, timeout_ms: int = 60_000) -> str:
    resp = context.request.post(
        url, data=body, timeout=timeout_ms,
        headers={
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "X-Same-Domain": "1", "Origin": BASE_URL, "Referer": f"{BASE_URL}/",
        },
    )
    return resp.text()


def _parse_rpc_result(text: str, rpc_id: str):
    if text.startswith(")]}'"):
        text = text[4:]
    for line in text.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            int(line); continue
        except ValueError:
            pass
        try:
            chunk = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(chunk, list):
            continue
        for item in chunk:
            if isinstance(item, list) and len(item) >= 3 and item[0] == "wrb.fr" and item[1] == rpc_id:
                if len(item) > 5 and isinstance(item[5], list) and 3 in item[5]:
                    raise RuntimeError(f"RPC Error 3 for {rpc_id}")
                result_str = item[2]
                if isinstance(result_str, str):
                    try:
                        return json.loads(result_str)
                    except json.JSONDecodeError:
                        return result_str
                return result_str
    return None


def _clean_json(raw: str) -> Optional[dict]:
    raw = unicodedata.normalize("NFC", raw)
    raw = re.sub(r"\[\d+\]", "", raw)
    raw = re.sub(r"```[a-z]*\n?", "", raw)
    start_idx = 0
    while True:
        pos = raw.find("{", start_idx)
        if pos == -1:
            break
        count, end_pos = 0, -1
        in_string = escape = False
        for i in range(pos, len(raw)):
            c = raw[i]
            if escape:
                escape = False; continue
            if c == "\\":
                escape = True; continue
            if c == '"':
                in_string = not in_string; continue
            if not in_string:
                if c == '{':
                    count += 1
                elif c == '}':
                    count -= 1
                    if count == 0:
                        end_pos = i; break
        if end_pos != -1:
            try:
                return json.loads(raw[pos:end_pos + 1])
            except json.JSONDecodeError:
                pass
        start_idx = pos + 1
    return None


# ── NLM worker (adapted — no SQLite) ─────────────────────────────────────────

class NLMWorker:
    def __init__(self, worker_id: int, auth: dict):
        self.worker_id = worker_id
        self.auth = auth
        self._browser = self._context = self._page = None
        self._notebook_id = self._bl = self._csrf = self._sid = None

    def start(self, playwright):
        self._browser = playwright.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-blink-features=AutomationControlled"],
        )
        self._context = self._browser.new_context(
            storage_state=str(STORAGE_STATE_PATH),
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        )
        self._page = self._context.new_page()
        self._page.goto(BASE_URL, wait_until="domcontentloaded", timeout=30_000)
        self._page.wait_for_timeout(2_000)
        if "accounts.google.com" in self._page.url:
            raise RuntimeError(
                "Google auth expired.\n"
                f"Run the refresh_nlm_auth script to refresh {STORAGE_STATE_PATH}"
            )
        self._refresh_session()

    def stop(self):
        if self._context: self._context.close()
        if self._browser: self._browser.close()

    def _refresh_session(self):
        html = self._page.content()
        self._bl, self._csrf, self._sid = _get_session_params(html, self.auth)

    def _post(self, url, body, timeout_ms=60_000):
        return _post_rpc(self._context, url, body, timeout_ms)

    def _create_notebook(self) -> str:
        params = [f"NLM-Worker-{self.worker_id}", None, None, [2],
                  [1, None, None, None, None, None, None, None, None, None, [1]]]
        url  = _build_url(RPC_CREATE, self._bl, self._sid)
        body = _build_body(RPC_CREATE, params, self._csrf)
        result = _parse_rpc_result(self._post(url, body), RPC_CREATE)
        if not result or not isinstance(result, list) or len(result) < 3:
            raise RuntimeError(f"Worker {self.worker_id}: create notebook failed: {result}")
        return result[2]

    def _delete_notebook(self, notebook_id: str):
        self._refresh_session()
        url  = _build_url(RPC_DELETE_NB, self._bl, self._sid, f"/notebook/{notebook_id}")
        body = _build_body(RPC_DELETE_NB, [[notebook_id], [2]], self._csrf)
        self._post(url, body)

    def _upload_and_index(self, pdf_path: Path) -> str:
        nb_url = f"{BASE_URL}/notebook/{self._notebook_id}"
        self._page.goto(nb_url, wait_until="domcontentloaded", timeout=60_000)
        self._page.wait_for_timeout(3_000)
        self._refresh_session()
        self._page.keyboard.press("Escape")
        self._page.wait_for_timeout(1_000)

        self._page.wait_for_selector("button[aria-label='Add source']", timeout=15_000)
        self._page.click("button[aria-label='Add source']", force=True)
        self._page.wait_for_timeout(1_000)

        for sel in ["button:has-text('Upload')", "button:has-text('PDF')", "[role='menuitem']:has-text('Upload')"]:
            try:
                self._page.wait_for_selector(sel, timeout=3_000)
                with self._page.expect_file_chooser(timeout=5_000) as fc_info:
                    self._page.click(sel)
                fc_info.value.set_files(str(pdf_path))
                log.info(f"Worker {self.worker_id}: uploaded {pdf_path.name}")
                break
            except Exception:
                continue
        else:
            raise RuntimeError(f"Worker {self.worker_id}: could not find Upload button")

        return self._poll_indexing(pdf_path.name)

    def _poll_indexing(self, filename: str) -> str:
        deadline = time.time() + INDEX_POLL_MAX
        source_id = None
        while time.time() < deadline:
            time.sleep(INDEX_POLL_INTERVAL)
            url    = _build_url(RPC_GET_NB, self._bl, self._sid, f"/notebook/{self._notebook_id}")
            params = [self._notebook_id, None,
                      [2, None, None, [1, None, None, None, None, None, None, None, None, None, [1]]],
                      None, 1, [[None, None, []]]]
            body   = _build_body(RPC_GET_NB, params, self._csrf)
            result = _parse_rpc_result(self._post(url, body), RPC_GET_NB)
            if result and isinstance(result, list) and len(result) == 1 and isinstance(result[0], list):
                result = result[0]
            if not result or not isinstance(result, list) or len(result) < 2:
                continue
            sources = result[1] if len(result) > 1 else []
            if not sources:
                continue
            for src in sources:
                if not isinstance(src, list) or len(src) < 4:
                    continue
                src_id_list, src_name, _, status_marker = src[0], src[1], src[2], src[3]
                if src_name != filename:
                    continue
                if isinstance(src_id_list, list) and src_id_list:
                    source_id = src_id_list[0]
                if isinstance(status_marker, list) and len(status_marker) >= 2 and status_marker[1] == 2:
                    log.info(f"Worker {self.worker_id}: {filename} indexed (source {source_id})")
                    return source_id
        raise RuntimeError(f"Worker {self.worker_id}: indexing timed out for {filename}")

    def _query_and_wait(self) -> str:
        self._page.keyboard.press("Escape")
        self._page.wait_for_timeout(500)
        filled = False
        for sel in ['textarea[aria-label="Query box"]', 'textarea[placeholder="Start typing..."]', 'textarea.query-box']:
            try:
                self._page.wait_for_selector(sel, timeout=5_000)
                ok = self._page.evaluate(
                    """([selector, query]) => {
                        const ta = document.querySelector(selector);
                        if (!ta) return false;
                        ta.focus();
                        const setter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set;
                        setter.call(ta, query);
                        ta.dispatchEvent(new Event('input', {bubbles: true}));
                        ta.dispatchEvent(new Event('change', {bubbles: true}));
                        return true;
                    }""",
                    [sel, INSIDER_PROMPT],
                )
                if ok:
                    filled = True; break
            except Exception:
                continue
        if not filled:
            raise RuntimeError(f"Worker {self.worker_id}: could not fill query textarea")
        self._page.wait_for_timeout(500)
        self._page.keyboard.press("Enter")
        return self._poll_for_answer()

    def _poll_for_answer(self) -> str:
        deadline = time.time() + QUERY_TIMEOUT_MS / 1000
        last_stable = ""
        stable_since = 0.0
        prompt_end = "Your response MUST start with { and end with }"
        while time.time() < deadline:
            time.sleep(2)
            try:
                dom_text = self._page.inner_text("body")
            except Exception:
                continue
            prompt_end_pos = dom_text.find(prompt_end)
            if prompt_end_pos == -1:
                continue
            after_prompt = dom_text[prompt_end_pos + len(prompt_end):]
            json_start = after_prompt.find("{")
            if json_start == -1:
                continue
            candidate = after_prompt[json_start:json_start + 50_000]
            if candidate == last_stable:
                if time.time() - stable_since >= 5:
                    return candidate
            else:
                last_stable = candidate
                stable_since = time.time()
        raise RuntimeError(f"Worker {self.worker_id}: query timed out")

    def extract(self, article_id: int, pdf_path: Path) -> Optional[dict]:
        """Extract transactions from one PDF. Returns parsed dict or None on failure."""
        log.info(f"Worker {self.worker_id}: extracting article {article_id} ({pdf_path.name})")
        try:
            self._page.goto(BASE_URL, wait_until="domcontentloaded", timeout=30_000)
            self._page.wait_for_timeout(1_000)
            self._refresh_session()

            self._notebook_id = self._create_notebook()
            log.info(f"Worker {self.worker_id}: notebook {self._notebook_id} created")

            self._upload_and_index(pdf_path)
            raw = self._query_and_wait()
            data = _clean_json(raw)
            if not data:
                log.error(f"Worker {self.worker_id}: JSON parse failed for {article_id}")
            return data
        except Exception as e:
            log.error(f"Worker {self.worker_id}: failed on {article_id}: {e}")
            try:
                os.makedirs("C:/Users/Administrator/Playwright-Daily-News/reports/testing", exist_ok=True)
                screenshot_path = f"C:/Users/Administrator/Playwright-Daily-News/reports/testing/fail_{article_id}.png"
                self._page.screenshot(path=screenshot_path)
                log.info(f"Saved failure screenshot to {screenshot_path}")
            except Exception as se:
                log.error(f"Failed to save screenshot: {se}")
            return None
        finally:
            if self._notebook_id:
                try:
                    self._delete_notebook(self._notebook_id)
                    self._notebook_id = None
                except Exception as e:
                    log.warning(f"Worker {self.worker_id}: notebook delete failed: {e}")


# ── Thread worker ─────────────────────────────────────────────────────────────

_results_lock = threading.Lock()


def _thread_worker(worker_id: int, auth: dict, queue: list, queue_lock: threading.Lock, results: dict):
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        worker = NLMWorker(worker_id, auth)
        try:
            worker.start(p)
        except Exception as e:
            log.error(f"Worker {worker_id}: startup failed: {e}")
            return
        while True:
            with queue_lock:
                if not queue:
                    break
                item = queue.pop(0)
            article_id = item["article_id"]
            pdf_path   = item["pdf_path"]
            data = worker.extract(article_id, pdf_path)
            if data is None:
                log.error(f"Worker {worker_id} extraction failed. Re-starting browser context...")
                try:
                    worker.stop()
                except Exception:
                    pass
                try:
                    worker.start(p)
                except Exception as start_err:
                    log.error(f"Worker {worker_id} restart failed: {start_err}")
            with _results_lock:
                results.setdefault(article_id, []).append(data)
        worker.stop()
        log.info(f"Worker {worker_id}: done")


# ── Main pipeline ─────────────────────────────────────────────────────────────

def find_latest_json() -> Optional[Path]:
    # exclude already-extracted and formatted files
    matches = [
        p for p in sorted(glob.glob(str(Path(OUTDIR) / "hsx_insider_trading_*.json")))
        if not p.endswith("_extracted.json") and not p.endswith("_formatted.json")
    ]
    return Path(matches[-1]) if matches else None


def run(json_path: Optional[Path] = None, n_workers: int = 2, dry_run: bool = False):
    if not json_path:
        json_path = find_latest_json()
    if not json_path or not json_path.exists():
        log.error("No hsx_insider_trading_*.json found. Run hsx_insider_scraper.py first.")
        sys.exit(1)

    if not dry_run and not STORAGE_STATE_PATH.exists():
        log.error(
            f"NotebookLM auth not found at {STORAGE_STATE_PATH}\n"
            "Set up auth first: see README in VN-HSX-INSIDER-TRADING-CRAWL repo."
        )
        sys.exit(1)

    log.info(f"Reading {json_path}")
    records = json.loads(json_path.read_text(encoding="utf-8"))
    auth = json.loads(AUTH_JSON_PATH.read_text(encoding="utf-8")) if AUTH_JSON_PATH.exists() else {}

    # Download PDFs for all records that have pdf_urls
    queue: list[dict] = []
    for rec in records:
        article_id = rec.get("article_id")
        pdf_urls   = rec.get("pdf_urls") or []
        if not article_id or not pdf_urls:
            rec["transactions"] = []
            continue
        
        has_any_pdf = False
        for idx, pdf_url in enumerate(pdf_urls):
            filename = f"{article_id}_{idx}.pdf"
            pdf_path = PDF_DIR / filename
            if not pdf_path.exists():
                log.info(f"Downloading PDF for article {article_id} (part {idx})...")
                if not download_pdf(pdf_url, pdf_path):
                    continue
            else:
                log.info(f"PDF already cached: {pdf_path}")
            queue.append({"article_id": article_id, "pdf_path": pdf_path})
            has_any_pdf = True
            
        if has_any_pdf:
            rec["transactions"] = None  # placeholder, filled after extraction
        else:
            rec["transactions"] = []

    if not queue:
        log.info("No PDFs to extract.")
        _save(records, json_path)
        return

    log.info(f"Extracting {len(queue)} PDFs with {n_workers} worker(s)...")

    if dry_run:
        log.info("Dry-run: skipping NotebookLM extraction.")
        for item in queue:
            for rec in records:
                if rec.get("article_id") == item["article_id"]:
                    rec["transactions"] = []
    else:
        results: dict = {}
        queue_lock = threading.Lock()
        work_queue = list(queue)
        with ThreadPoolExecutor(max_workers=n_workers, thread_name_prefix="NLMWorker") as pool:
            futures = [
                pool.submit(_thread_worker, i, auth, work_queue, queue_lock, results)
                for i in range(n_workers)
            ]
            for f in as_completed(futures):
                try:
                    f.result()
                except Exception as e:
                    log.error(f"Worker thread error: {e}")

        # Merge extracted transactions back into records
        for rec in records:
            aid = rec.get("article_id")
            if aid in results:
                all_tx = []
                for extracted in results[aid]:
                    if extracted and isinstance(extracted, dict):
                        all_tx.extend(extracted.get("transactions", []))
                rec["transactions"] = all_tx

    _save(records, json_path)


def _save(records: list, json_path: Path):
    # Replace None placeholders
    for rec in records:
        if rec.get("transactions") is None:
            rec["transactions"] = []
    out_path = json_path.with_name(json_path.stem + "_extracted.json")
    out_path.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")
    n_with_tx = sum(1 for r in records if r.get("transactions"))
    log.info(f"Saved {out_path} — {n_with_tx}/{len(records)} records have transactions")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="HSX NLM PDF extractor")
    parser.add_argument("--input",   type=Path, default=None, help="Path to hsx_insider_trading_*.json")
    parser.add_argument("--workers", type=int,  default=2,    help="Parallel NLM workers")
    parser.add_argument("--dry-run", action="store_true",      help="Skip NLM, test download only")
    args = parser.parse_args()
    run(json_path=args.input, n_workers=args.workers, dry_run=args.dry_run)
